---
language: python
services: docker

cache:
  - pip

env:
  global:
    - ROLE_NAME: git-server
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: fedora31
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME daveol.$ROLE_NAME
  - cd daveol.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
