---
- include_tasks: "{{ item }}"
  loop: "{{ q('first_found', params, errors='ignore') }}"
  vars:
    params:
      files:
        - "setup-{{ ansible_os_family }}.yml"
      paths:
        - 'tasks'
      skip: true

- include_tasks: user.yml

- include_tasks: commands.yml

- include_tasks: repo.yml
  loop: "{{ git_repos }}"
  loop_control:
    loop_var: git_repo