---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Ensure git is installed
  apt:
    name: "{{ git_packages }}"
    state: present

- name: Ensure git-cvs is installed
  apt:
    name: "{{ git_cvs_packages }}"
    state: present
  when: git_server_enable_cvs
