---
- name: Converge
  hosts: all
  become: true

  vars:
    git_repos:
      - path: test.git

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 86400
      when: ansible_os_family == "Debian"

    - name: Install SSH (Debian)
      package:
        name:
          - openssh-client
          - openssh-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Install SSH (RedHat)
      package:
        name:
          - openssh-server
          - openssh-clients
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create SSH keys
      user:
        name: "{{ ansible_env['USER'] }}"
        generate_ssh_key: yes
      register: user_ssh_key

    - name: Set SSH keys
      set_fact:
        git_keys:
          - "{{ user_ssh_key.ssh_public_key }}"

    - name: Enable SSH server
      service:
        name: sshd
        state: started

  roles:
    - role: daveol.git-server

  post_tasks:
    - name: Make sure we can login
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/run/nologin
        - /etc/nologin
        - /run/nologin
      when: ansible_os_family == "RedHat"

    - name: Check we can checkout the git repository
      command: git git@localhost:test.git /tmp/test # noqa 303