---
- name: Converge
  hosts: all
  become: true

  vars:
    git_repos:
      - path: test.git

  pre_tasks:
    - name: Create SSH keys
      user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
      register: user_ssh_key

    - name: Set SSH keys
      set_fact:
        git_keys:
          - "{{ user_ssh_key.ssh_public_key }}"

  roles:
    - role: daveol.git-server

  post_tasks:
    - name: Check we can checkout the git repository
      git:
        accept_hostkey: yes
        repo: "git@localhost:test.git"
        dest: /tmp/test
        version: master
