---
- name: Converge
  hosts: all
  become: true

  vars:
    git_repos:
      - path: test.git

  pre_tasks:
    # The Fedora 30+ container images have only C.UTF-8 installed
    - name: Set database locale if using Fedora 30+ or RedHat 8+
      set_fact:
        git_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFhyob72VL/7+5Jocjoqb9KtWwiUy6DM5/AN/jZjXZeL dolsthoorn@esri.nl

  roles:
    - role: daveol.git-server

  post_tasks:
    - name: Check we can checkout the git repository
      git:
        accept_hostkey: yes
        repo: "git@localhost:test.git"
        dest: /tmp/test
        version: master
